import type { Client } from "@/types/client";
import { activeTenant } from "./tenant";

export const clients: Client[] = [
  {
    id: "cli_olivia",
    tenantId: activeTenant.id,
    name: "Olivia Sanders",
    email: "olivia.s@example.com",
    phone: "+1 (415) 555-0211",
    initials: "OS",
    totalVisits: 14,
    lastVisitISO: "2026-05-18",
    lifetimeValueCents: 142000,
    tags: ["VIP"],
  },
  {
    id: "cli_ethan",
    tenantId: activeTenant.id,
    name: "Ethan Park",
    email: "ethan.park@example.com",
    phone: "+1 (415) 555-0234",
    initials: "EP",
    totalVisits: 6,
    lastVisitISO: "2026-05-22",
    lifetimeValueCents: 48000,
    tags: ["Regular"],
  },
  {
    id: "cli_mia",
    tenantId: activeTenant.id,
    name: "Mia Tanaka",
    email: "mia.t@example.com",
    phone: "+1 (415) 555-0288",
    initials: "MT",
    totalVisits: 22,
    lastVisitISO: "2026-05-25",
    lifetimeValueCents: 286000,
    tags: ["VIP", "Color"],
  },
  {
    id: "cli_noah",
    tenantId: activeTenant.id,
    name: "Noah Brennan",
    email: "noah.b@example.com",
    phone: "+1 (415) 555-0102",
    initials: "NB",
    totalVisits: 3,
    lastVisitISO: "2026-04-30",
    lifetimeValueCents: 18000,
    tags: ["New"],
  },
  {
    id: "cli_zoe",
    tenantId: activeTenant.id,
    name: "Zoe Alvarez",
    email: "zoe.a@example.com",
    phone: "+1 (415) 555-0177",
    initials: "ZA",
    totalVisits: 9,
    lastVisitISO: "2026-05-26",
    lifetimeValueCents: 91500,
    tags: ["Regular"],
  },
  {
    id: "cli_kai",
    tenantId: activeTenant.id,
    name: "Kai Robinson",
    email: "kai.r@example.com",
    phone: "+1 (415) 555-0156",
    initials: "KR",
    totalVisits: 1,
    lastVisitISO: null,
    lifetimeValueCents: 0,
    tags: ["Lead"],
  },
  {
    id: "cli_anaya",
    tenantId: activeTenant.id,
    name: "Anaya Patel",
    email: "anaya.p@example.com",
    phone: "+1 (415) 555-0145",
    initials: "AP",
    totalVisits: 11,
    lastVisitISO: "2026-05-20",
    lifetimeValueCents: 132000,
    tags: ["Wellness"],
  },
  {
    id: "cli_diego",
    tenantId: activeTenant.id,
    name: "Diego Marín",
    email: "diego.m@example.com",
    phone: "+1 (415) 555-0193",
    initials: "DM",
    totalVisits: 4,
    lastVisitISO: "2026-05-10",
    lifetimeValueCents: 38000,
    tags: ["Barber"],
  },
];
