import type { Professional } from "@/types/professional";
import { activeTenant } from "./tenant";

export const professionals: Professional[] = [
  {
    id: "pro_amelia",
    tenantId: activeTenant.id,
    name: "Amelia Hart",
    role: "Senior Stylist",
    email: "amelia@glowstudio.co",
    phone: "+1 (415) 555-0181",
    initials: "AH",
    specialties: ["Color", "Balayage", "Cuts"],
    workingDays: "Mon – Fri",
    workingHours: "09:00 – 18:00",
    active: true,
  },
  {
    id: "pro_jordan",
    tenantId: activeTenant.id,
    name: "Jordan Lee",
    role: "Barber",
    email: "jordan@glowstudio.co",
    phone: "+1 (415) 555-0114",
    initials: "JL",
    specialties: ["Fades", "Beard sculpting"],
    workingDays: "Tue – Sat",
    workingHours: "10:00 – 19:00",
    active: true,
  },
  {
    id: "pro_nora",
    tenantId: activeTenant.id,
    name: "Nora Chen",
    role: "Esthetician",
    email: "nora@glowstudio.co",
    phone: "+1 (415) 555-0167",
    initials: "NC",
    specialties: ["Facials", "Peels", "Skincare"],
    workingDays: "Wed – Sun",
    workingHours: "11:00 – 20:00",
    active: true,
  },
  {
    id: "pro_sasha",
    tenantId: activeTenant.id,
    name: "Sasha Romero",
    role: "Nail Artist",
    email: "sasha@glowstudio.co",
    phone: "+1 (415) 555-0125",
    initials: "SR",
    specialties: ["Gel", "Nail art", "Pedicure"],
    workingDays: "Mon, Wed – Sat",
    workingHours: "09:30 – 18:30",
    active: true,
  },
  {
    id: "pro_marcus",
    tenantId: activeTenant.id,
    name: "Marcus Webb",
    role: "Massage Therapist",
    email: "marcus@glowstudio.co",
    phone: "+1 (415) 555-0198",
    initials: "MW",
    specialties: ["Deep tissue", "Sports", "Relaxation"],
    workingDays: "Thu – Mon",
    workingHours: "12:00 – 20:00",
    active: true,
  },
];
