import type { Service } from "@/types/service";
import { activeTenant } from "./tenant";

export const services: Service[] = [
  {
    id: "svc_haircut",
    tenantId: activeTenant.id,
    name: "Signature Haircut",
    description: "Consultation, wash, precision cut, and finish.",
    category: "Hair",
    durationMinutes: 60,
    priceCents: 8500,
    professionalIds: ["pro_amelia", "pro_jordan"],
    active: true,
  },
  {
    id: "svc_color",
    tenantId: activeTenant.id,
    name: "Full Color",
    description: "Single-process color refresh with gloss treatment.",
    category: "Hair",
    durationMinutes: 120,
    priceCents: 18500,
    professionalIds: ["pro_amelia"],
    active: true,
  },
  {
    id: "svc_balayage",
    tenantId: activeTenant.id,
    name: "Balayage",
    description: "Hand-painted highlights for a sun-kissed finish.",
    category: "Hair",
    durationMinutes: 180,
    priceCents: 28000,
    professionalIds: ["pro_amelia"],
    active: true,
  },
  {
    id: "svc_beard",
    tenantId: activeTenant.id,
    name: "Beard Sculpt",
    description: "Trim, line-up, and hot-towel finish.",
    category: "Barber",
    durationMinutes: 30,
    priceCents: 4500,
    professionalIds: ["pro_jordan"],
    active: true,
  },
  {
    id: "svc_facial",
    tenantId: activeTenant.id,
    name: "Glow Facial",
    description: "Deep cleanse, exfoliation, and hydrating mask.",
    category: "Skin",
    durationMinutes: 75,
    priceCents: 13500,
    professionalIds: ["pro_nora"],
    active: true,
  },
  {
    id: "svc_peel",
    tenantId: activeTenant.id,
    name: "Chemical Peel",
    description: "Resurfacing treatment for radiance and tone.",
    category: "Skin",
    durationMinutes: 60,
    priceCents: 16000,
    professionalIds: ["pro_nora"],
    active: true,
  },
  {
    id: "svc_gel",
    tenantId: activeTenant.id,
    name: "Gel Manicure",
    description: "Shape, cuticle care, gel polish in any shade.",
    category: "Nails",
    durationMinutes: 60,
    priceCents: 6500,
    professionalIds: ["pro_sasha"],
    active: true,
  },
  {
    id: "svc_pedi",
    tenantId: activeTenant.id,
    name: "Spa Pedicure",
    description: "Soak, scrub, massage, and polish.",
    category: "Nails",
    durationMinutes: 60,
    priceCents: 7500,
    professionalIds: ["pro_sasha"],
    active: true,
  },
  {
    id: "svc_massage",
    tenantId: activeTenant.id,
    name: "Deep Tissue Massage",
    description: "60-minute targeted therapeutic massage.",
    category: "Wellness",
    durationMinutes: 60,
    priceCents: 12000,
    professionalIds: ["pro_marcus"],
    active: true,
  },
  {
    id: "svc_relax",
    tenantId: activeTenant.id,
    name: "Relaxation Massage",
    description: "Full-body Swedish technique to unwind.",
    category: "Wellness",
    durationMinutes: 90,
    priceCents: 15500,
    professionalIds: ["pro_marcus"],
    active: false,
  },
];
